<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="asem" nsURI="edu.kit.ipd.sdq.metamodels.asem" nsPrefix="asem">
  <eClassifiers xsi:type="ecore:EClass" name="Dummy"/>
  <eSubpackages name="base" nsURI="edu.kit.ipd.sdq.metamodels.asem.base" nsPrefix="base">
    <eClassifiers xsi:type="ecore:EClass" name="Named" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" unique="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="" iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypedElement" eSuperTypes="#//base/Identifiable #//base/Named">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//classifiers/Classifier"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="classifiers" nsURI="edu.kit.ipd.sdq.metamodels.asem.classifiers"
      nsPrefix="classifiers">
    <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="#//base/Named">
      <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
          eType="#//dataexchange/Method" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="ComposedType" eSuperTypes="#//classifiers/Classifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveType" eType="#//primitivetypes/PrimitiveType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberElements" unique="false"
          defaultValueLiteral="0" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="#//base/Identifiable #//classifiers/Classifier #//base/Named">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typedElements" upperBound="-1"
          eType="#//base/TypedElement" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//classifiers/Component"/>
    <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//classifiers/Component"/>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//classifiers/Classifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
          eType="#//dataexchange/Method"/>
    </eClassifiers>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="InterruptTask" eSuperTypes="#//classifiers/Task"/>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="InitTask" eSuperTypes="#//classifiers/Task"/>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="SoftwareTask" eSuperTypes="#//classifiers/Task"/>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="PeriodicTask" eSuperTypes="#//classifiers/Task">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" unique="false"
          defaultValueLiteral="0" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" unique="false"
          defaultValueLiteral="0" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="TimeTableTask" eSuperTypes="#//classifiers/Task"/>
  </eSubpackages>
  <eSubpackages name="dataexchange" nsURI="edu.kit.ipd.sdq.metamodels.asem.dataexchange"
      nsPrefix="dataexchange">
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//base/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readable" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="writable" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//dataexchange/Variable"/>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//base/Identifiable #//base/Named">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//dataexchange/Parameter" containment="true" resolveProxies="false"
          eOpposite="#//dataexchange/Parameter/method"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//dataexchange/ReturnType"
          containment="true" resolveProxies="false" eOpposite="#//dataexchange/ReturnType/method"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
          eType="#//dataexchange/Variable" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//dataexchange/Variable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//dataexchange/Method"
          eOpposite="#//dataexchange/Method/parameters"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnType" eSuperTypes="#//base/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//dataexchange/Method"
          eOpposite="#//dataexchange/Method/returnType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//base/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="SystemConstant" eSuperTypes="#//dataexchange/Constant"/>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="Argument" eSuperTypes="#//dataexchange/Variable"/>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//dataexchange/Variable"/>
    <!-- changes made by uskui -->
    <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//dataexchange/Variable"/>
  </eSubpackages>
  <eSubpackages name="primitivetypes" nsURI="edu.kit.ipd.sdq.metamodels.asem.primitivetypes"
      nsPrefix="primitivetypes">
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//classifiers/Classifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="ContinuousType" eSuperTypes="#//primitivetypes/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnsignedDiscreteType" eSuperTypes="#//primitivetypes/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="SignedDiscreteType" eSuperTypes="#//primitivetypes/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//primitivetypes/PrimitiveType"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeRepository" eSuperTypes="#//base/Named">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveTypes" upperBound="-1"
          eType="#//primitivetypes/PrimitiveType" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
